name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
  repository_dispatch:
    types: [ 'movie-harness-change' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run clean
      - run: npm run build
  e2e:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        neo4j-version: [ "4.4", "4.4-enterprise", "5", "5-enterprise" ]
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        ports: [ "7687:7687" ]
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: "neo4j/abcdefghi"
        options: >-
          --name neo4j-e2e
          --health-cmd "cypher-shell -u neo4j -p abcdefghi 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-start-period 10s
          --health-retries 5
          --volume /tmp:/movies
    steps:
      - name: Download dataset
        run: curl --fail --output /tmp/movies.cypher https://raw.githubusercontent.com/neo4j-graph-examples/movies/7e75003d2d32bf42ef9c740d1321a310fac1d1a6/scripts/movies.cypher
      - name: Import dataset
        run: docker exec --interactive neo4j-e2e cypher-shell -u neo4j -p abcdefghi --file /movies/movies.cypher
      - name: Check out project sources
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check out test harness sources
        uses: actions/checkout@v4
        with:
          repository: neo4j-examples/movies-harness
          path: e2e
          ref: ${{ github.event.client_payload.sha }}
      - uses: cypress-io/github-action@v6
        env:
          NEO4J_VERSION: ${{ matrix.neo4j-version }}
          NEO4J_URI: bolt://localhost
          NEO4J_DATABASE: "neo4j"
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: abcdefghi
        with:
          working-directory: e2e
          browser: chrome
          start: npm --prefix .. start
